 const IndianCities= [
    'Ahmedabad',
    'Port Blair',
    'Kolkata',
    'Mumbai',
    'Delhi',
    'Banglore',
    'Chennai',
    'Pune',
    'Shrinagar',
    'Dehradun',
    'Dharmashala',
    'Chandigahr',
    'Lakhnaw',
    'VAranasi',
    'Hydrabad',
    'Guwahati',
    'Vishakhapatnam',
    'Jaipur',
    "Surat",
    'Nagpur',
    'Ranchi'
]

const AbroadCities = [
    'Abu Dhabi',
    "Algiers",
    'Aalborg',
    'Amsterdam',
    'Athens',
    'Atlanta ',
    'Auckland',
    'Bagdhad',
    'Bahamas',
    'Baltomore',
    'Bangkok',
    'Barcelona',
    'Beijing',
    'Beirut ',
    'Berlin',
    'Bermunda',
    'Bostan',
    'Brisbane',
    'Budapest ',
    'Cairo ',
    'Cambrigde',
    'Canberra',
    'Cape Town',
    'Chicago (IL)',
    'Cleveland',
    'Colombo',
    'Denver',
    'Dhaka',
    'Derby',
    'Detroit',
    'Dubai',
    'Durban',
    'Edinburgh', 'El Dorado', 'Florance', 'Fukushima', 'Geneva',  'Hamburg', 'Harare', 'Helsinki','Hong Kong', "Houston",
'islamabad', 'istanbul','Jaksonville', 'jakarta','jerusalem', 'Johannesburg','Kabul', 'KAiro', 'Karachi',
'Kathmandu', 'Kiev', 'Kuala Lampur', 'Kuwait City', ' Lagos', 'Lahor', 'Las Vegas', 'Lisbon', 'LiverPool', 'London', 'Los Angles', 'Macao','Madrid','Manchester', 'Mauritius', 'Melbourn','Mexico city','Maimi','Milan','Monaco','Moscow','Muscat','Nagasaki', 'Nairobi', 'New York',
'Oakland','Oslo','Panama City', 'Paris', 'perth', 'Peshawar', ' Pittsburg', 'Port of Spain', 'Parague', 'Rio de Janerio', 'Riyadh', 'Rome', 'San Diego', 'San Francisco', 'Sao paulo', 'Shanghai', 'Singapore', 'Stockholm', 'Sydney','Taipei','Tashket','Tehran','Thimpu','Tokyo','Toronto','Trinidad','Vancover',
'Venice','Victoria','Vienna','Washington D.C.','Wellington','Wuhan','Zurich'

]

